version: '3.8'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: onlinebookstore


